MODEL:
  PRETRAIN_CHOICE: 'random_init'
  PRETRAIN_PATH: './pretrained_model/resnet50-19c8e357.pth'
  LAST_STRIDE: 2
  NECK: 'no'
  METRIC_LOSS_TYPE: 'softmax'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'efficient'
  ARCH: 'b7' # b5 b7
  # DEVICE_ID: "2"


INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.0 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('anti_mask')
  ROOT_DIR: "../extra_data/pts"
DATALOADER:
  SAMPLER: 'softmax'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 20
  BASE_LR: 0.01 # 0.0001

  # CLUSTER_MARGIN: 0.3

  # CENTER_LR: 0.5
  # CENTER_LOSS_WEIGHT: 0.0005

  # RANGE_K: 2
  # RANGE_MARGIN: 0.3
  # RANGE_ALPHA: 0
  # RANGE_BETA: 1
  # RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 128
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [10, 15]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 20
  EVAL_PERIOD: 4

TEST:
  IMS_PER_BATCH: 1
  RE_RANKING: 'no'
  WEIGHT: "../logs/anti_b5_era_03ß/checkpoint_19.pth"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "../logs/anti_b7"

